FPS = 60
WIDTH, HEIGHT = 1400, 800
RECTANGLE_WIDTH_CAP = 650
FULL_SCREEN_VIEW = True
BACKGROUND = True
RESIZABLE = True
RECT_COMBO_DISPLAY = False
HIDE_PERFECT = False
NUMBER_OF_RECORDS = 4

DEFAULT_CIRCLE_SIZE = 20
